language: python
# command to install dependencies

python: 3.8

install:
  - pip install -r requirements.txt
  - pip install -e .

# command to run tests
script:
  - coverage run -m pytest

# Push the results back to codecov (when repo is public)
#after_success:
#  - codecov